# Generated by Django 3.2.9 on 2021-12-01 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('status', models.CharField(choices=[('Leave', 'Leave'), ('Work From Home', 'Work From Home'), ('Office', 'Office'), ('Holliday', 'Holliday')], default='Office', max_length=50)),
                ('time', models.CharField(choices=[('9:00 AM to 05:00 PM', '9:00 AM to 05:00 PM'), ('09:00 AM to 01:00 PM', '9:00 AM to 01:00 PM'), ('01:00 PM to 05:00 PM', '01:00 PM to 05:00 PM')], default='Full Day', max_length=50)),
                ('completed', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.BooleanField(blank=True, default=False, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('ifsccode', models.CharField(blank=True, max_length=100, null=True)),
                ('accountnumber', models.CharField(blank=True, max_length=100, null=True)),
                ('mob', models.CharField(blank=True, max_length=20, null=True)),
                ('dob', models.DateField(null=True)),
                ('office', models.CharField(blank=True, choices=[('KOCHIN', 'KOCHIN'), ('TRIVANDRUM', 'TRIVANDRUM')], default='KOCHIN', max_length=100, null=True)),
                ('language', models.CharField(blank=True, choices=[('PYTHON', 'PYTHON'), ('JAVA', 'JAVA')], default='PYTHON', max_length=200, null=True)),
                ('status', models.CharField(default='alive', max_length=50)),
                ('datejoined', models.DateField(auto_now_add=True, null=True)),
                ('profile_picture', models.ImageField(default='dora.jpg', upload_to='')),
                ('completed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(blank=True, max_length=200, null=True)),
                ('timefrom', models.CharField(max_length=50, null=True)),
                ('timeto', models.CharField(max_length=50, null=True)),
                ('works', models.CharField(max_length=500)),
                ('uptime', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nvt.attendance')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('days', models.IntegerField(null=True)),
                ('reson', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(default='requested', max_length=50)),
                ('adminreson', models.CharField(blank=True, max_length=500, null=True)),
                ('view', models.CharField(default='adminnotviewed', max_length=20, null=True)),
                ('emp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nvt.emp')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='emp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nvt.emp'),
        ),
    ]
