# Generated by Django 3.2.9 on 2023-03-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='language',
            field=models.CharField(blank=True, choices=[('PHP', 'PHP'), ('PYTHON', 'PYTHON'), ('JAVA', 'JAVA'), ('ANDROID', 'ANDROID'), ('OFFICE STAFF', 'OFFICE STAF'), ('DATA SCIENCE', 'DATA SCIENCE'), ('.NET', '.NET')], default='PYTHON', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='office',
            field=models.CharField(blank=True, choices=[('COCHIN', 'COCHIN'), ('TRIVANDRUM', 'TRIVANDRUM')], default='COCHIN', max_length=100, null=True),
        ),
    ]
