# Generated by Django 3.2.9 on 2023-03-13 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nvt', '0003_auto_20230313_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='Profile',
            new_name='profile',
        ),
    ]
