# Generated by Django 3.2.9 on 2023-03-13 09:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nvt', '0006_auto_20230313_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
