# Generated by Django 3.2.9 on 2023-03-13 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nvt', '0007_alter_course_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile',
            new_name='course',
        ),
    ]
