# Generated by Django 3.2.9 on 2023-03-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvt', '0008_rename_profile_profile_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
