# Generated by Django 3.2.9 on 2023-03-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvt', '0009_alter_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='parent_contact',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='parent_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='semester',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Staff', 'Staff'), ('Parent', 'Parent'), ('Admin', 'Admin')], max_length=200, null=True),
        ),
    ]
