# Generated by Django 3.2.9 on 2023-03-13 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nvt', '0010_auto_20230313_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='course',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mob',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='parent_contact',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='parent_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='reg_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='semester',
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.BooleanField(blank=True, default=False, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('parent_name', models.CharField(blank=True, max_length=200, null=True)),
                ('parent_contact', models.CharField(blank=True, max_length=200, null=True)),
                ('semester', models.CharField(blank=True, max_length=200, null=True)),
                ('reg_number', models.CharField(blank=True, max_length=20, null=True)),
                ('mob', models.CharField(blank=True, max_length=20, null=True)),
                ('dob', models.DateField(null=True)),
                ('status', models.CharField(default='alive', max_length=50)),
                ('datejoined', models.DateField(auto_now_add=True, null=True)),
                ('profile_picture', models.ImageField(default='dora.jpg', upload_to='')),
                ('completed', models.BooleanField(default=False)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nvt.course')),
            ],
        ),
    ]
