# Generated by Django 3.2.9 on 2023-03-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvt', '0012_auto_20230313_2255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='datejoined',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='student',
            name='joining_date',
            field=models.DateField(null=True),
        ),
    ]
