# Generated by Django 4.1.7 on 2023-03-18 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nvt', '0015_subject_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('mob', models.CharField(blank=True, max_length=20, null=True)),
                ('dob', models.DateField(null=True)),
                ('status', models.CharField(default='alive', max_length=50)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('profile_picture', models.ImageField(default='dora.jpg', upload_to='')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nvt.student')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
