# Generated by Django 4.1.7 on 2023-03-21 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nvt', '0019_remove_leave_profile_remove_leave_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_leave', to=settings.AUTH_USER_MODEL),
        ),
    ]
