# Generated by Django 4.1.7 on 2023-03-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvt', '0023_alter_attendance_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50, null=True)),
            ],
        ),
    ]
