# Generated by Django 4.1.7 on 2023-03-23 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nvt', '0028_reference_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nvt.course'),
        ),
    ]
