# Generated by Django 4.1.7 on 2023-03-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='attachment',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
